### ISSUE TITLE
碳汇交易/订单列表中，“数量”应该显示为未成交的部分

### ISSUE THREAD

**Issue by zhaohuijuan001** [ECO2Ledger/eco2-apps#115]
碳汇交易/订单列表中，“数量”应该显示为未成交的部分，对着交易的进行，即时变更
单位根据实际的数量，匹配的显示为：克，千克，吨。
![image](https://user-images.githubusercontent.com/61004114/100059233-afbe7000-2e65-11eb-9ee6-70e5a81da2f2.png)

**Comment by my9527** [comment]
done

**Comment by zhaohuijuan001** [comment]
bug已修复，关闭
