### ISSUE TITLE
买碳汇后，确认交易的弹出框不消失，继续确认会重复购买

### ISSUE THREAD

**Issue by zhaohuijuan001** [ECO2Ledger/eco2-apps#121]
买碳汇后，确认交易的弹出框不消失，继续确认会重复购买
可以看到确认交易的弹出框提示“1/3”，每次都点击“签名并提交”，会购买3笔
期望结果：用户只需要成交单笔
![image](https://user-images.githubusercontent.com/61004114/100193722-50c52d80-2f2f-11eb-9d64-c54c9bdcab08.png)

**Comment by my9527** [comment]
done

**Comment by zhaohuijuan001** [comment]
bug已修复，关闭
