### ISSUE TITLE
资产发行：点击资产名称，应该跳转资产审核页面

### ISSUE THREAD

**Issue by zhaohuijuan001** [ECO2Ledger/eco2-apps#124]
资产发行：
碳汇项目列表，点击项目名称，应该跳转到碳汇项目的审核页面。
资产列表中，点击资产名称，应该跳转资产审核页面。
当前跳转的是，我的资产详情页
<img width="1030" alt="image" src="https://user-images.githubusercontent.com/61004114/100423682-3e3b1900-3041-11eb-8804-0a45f618b0c5.png">

**Comment by my9527** [comment]
资产详情中缺少 proposalId , 跳转后无法获取投票情况

**Comment by zhaohuijuan001** [comment]
经确认，当前实现可以接受，bug关闭
