### ISSUE TITLE
左侧导航栏，每个模块的icon, 请根据设计图实现

### ISSUE THREAD

**Issue by zhaohuijuan001** [ECO2Ledger/eco2-apps#129]
左侧导航栏，每个模块的icon, 请根据设计图实现：请看附件zip文件
[导航栏icon.zip](https://github.com/ECO2Ledger/eco2-apps/files/5628139/icon.zip)

![image](https://user-images.githubusercontent.com/61004114/100853091-50dea380-34c2-11eb-958c-d4bc0802c349.png)

**Comment by my9527** [comment]
提供svg 的icon

**Comment by zhaohuijuan001** [comment]
[导航栏iconSVG格式.zip](https://github.com/ECO2Ledger/eco2-apps/files/5902141/iconSVG.zip)

**Comment by zhaohuijuan001** [comment]
复测结果_2021/2/24:
1. icon与文字增加一点间距，10px就够
2. 文字和icon，需要垂直居中对齐
3. 请替换“钱包”的icon, 见附件
4. “资产发行”的icon始终显示绿色，未区分“选中/未选中”，请修改
![image](https://user-images.githubusercontent.com/61004114/108974661-a214c280-76c0-11eb-8b2f-4486761b8d98.png)

**Comment by zhaohuijuan001** [comment]
复测结果0301：
问题 1,2,4 已修改，请帮忙修改3： 替换“钱包”的icon, 见附件 （上边zip包）

**Comment by zhaohuijuan001** [comment]
Bug已修复，关闭

**Comment by zhaohuijuan001** [comment]
复测结果_2021/6/17:
钱包，JS的icon需调整，按需求实现

**Comment by zhaohuijuan001** [comment]
复测结果_2021/6/17:
钱包，JS的icon需调整，按需求实现
请看下方完整的导航栏icon, 
[导航栏icon (2).zip](https://github.com/ECO2Ledger/eco2-apps/files/6668343/icon.2.zip)
包含新钱包的icon
