### ISSUE TITLE
选择资产：转账页面，资产选项列表中，包含审核中的碳汇资产

### ISSUE THREAD

**Issue by zhaohuijuan001** [ECO2Ledger/eco2-apps#13]
碳中和页面，转账页面中，选择资产下拉列表：
包含了：MMNN（2020）， MMNN（2021） 等正在审核中的资产

应该为：审核通过，已经发行的资产。
（需求PRD）下拉可选项为：所有我不为 0 的资产，包括 标准资产和碳汇资产
<img width="576" alt="选择资产下拉列表" src="https://user-images.githubusercontent.com/61004114/96535829-52af2780-12c5-11eb-84b0-22dce9ea88f9.png">

**Comment by zhaohuijuan001** [comment]
更新bug描述：
转账页面，资产选项列表中，包含审核中的碳汇资产
包含了：MMNN（2020）， MMNN（2021） 等正在审核中的资产

应该为：审核通过，已经发行的碳汇资产。
（需求PRD）下拉可选项为：所有我不为 0 的资产，包括ECO2，标准资产和碳汇资产

**Comment by cryptomancc** [comment]
应该从/potential_balances获取可用于碳中和的资产列表，过滤出type为carbon的

**Comment by zhaohuijuan001** [comment]
bug已修复
