### ISSUE TITLE
给提案添接口加必须的字段

### ISSUE THREAD

**Issue by cryptomancc** [ECO2Ledger/eco2-apps#131]
### 接口返回值根字段

- pending：待提案数量
- voting：审批中数量
- closed：已结束数量
- total：总量

### 每个proposal元素增加如下字段：
- state：0/待提案, 1/审批中 2/已结束
- approved：undefined/投票结果未知，0/拒绝，1/通过
- ayes：赞同数量
- nays：不赞同数量

### 新增query字段

- state：undefined/全部，其他同上

**Comment by zhaohuijuan001** [comment]
已实现，bug关闭
