### ISSUE TITLE
我的挂单列表中，“数量”应为初始挂单总量，保持不变

### ISSUE THREAD

**Issue by zhaohuijuan001** [ECO2Ledger/eco2-apps#132]
我的挂单列表中，“数量”应为初始挂单总量，保持不变
这一点与全部挂单列表不同，要区分开
![image](https://user-images.githubusercontent.com/61004114/101593767-7839f100-3a2b-11eb-91bd-0fdb20601221.png)

**Comment by my9527** [comment]
done

**Comment by zhaohuijuan001** [comment]
bug已修复，关闭
