### ISSUE TITLE
碳汇项目已通过，但未结案时，不应该出现在“注册碳汇资产”的项目列表里

### ISSUE THREAD

**Issue by zhaohuijuan001** [ECO2Ledger/eco2-apps#133]
碳汇项目AAACCC，已有2人通过，状态为“已通过”，但是没有结案。
此时，项目发起人Bob，选择注册碳汇资产，项目列表中显示了该项目，填写完全部信息后，提交失败。

期望结果：已通过，未结案的项目，不应该出现在“注册碳汇资产”的项目列表里
![image](https://user-images.githubusercontent.com/61004114/101600915-f18b1100-3a36-11eb-845f-0e839e51a9dc.png)

**Comment by my9527** [comment]
done

**Comment by zhaohuijuan001** [comment]
bug已修复，关闭
