### ISSUE TITLE
普通用户，无权限对提案进行操作，按钮不应显示

### ISSUE THREAD

**Issue by zhaohuijuan001** [ECO2Ledger/eco2-apps#140]
普通用户，无权限对提案进行操作，按钮不应显示
![image](https://user-images.githubusercontent.com/61004114/101726629-e0510b80-3aed-11eb-9426-d9a0e17e8bd3.png)

**Comment by my9527** [comment]
done

**Comment by zhaohuijuan001** [comment]
bug已修复，关闭
