### ISSUE TITLE
提案详情页，删除“全部资产/注册碳汇项目...”等栏目

### ISSUE THREAD

**Issue by zhaohuijuan001** [ECO2Ledger/eco2-apps#142]
提案详情页，删除“全部资产、注册碳汇项目、注册碳汇资产，我发行的资产”等栏目
![image](https://user-images.githubusercontent.com/61004114/101728180-e5638a00-3af0-11eb-86ea-116d0311d225.png)

**Comment by my9527** [comment]
done

**Comment by zhaohuijuan001** [comment]
bug已修复
