### ISSUE TITLE
设置” 频道内，一系列改动

### ISSUE THREAD

**Issue by zhaohuijuan001** [ECO2Ledger/eco2-apps#16]
设置” 频道内：
1. 取消 “元数据”、“开发者” 功能模块; 
2. “翻译” 功能 ==调整为==> 选择语⾔； 提供默认：简体中⽂、英⽂ 的语⾔选项； 
3. “地址前缀” 默认调整为 “ Ex ”开头的前缀；
4. Token 名称 从现在的 Unit 调整为 ECO2 ；
<img width="524" alt="设置" src="https://user-images.githubusercontent.com/61004114/96548349-47b5c080-12e0-11eb-9292-ff15a8a09597.png">

**Comment by cryptomancc** [comment]
1. 元数据和开发者暂时不取消
3. 地址前缀由后端控制，但因为波卡的地址生成机制，目前无法定制字母前缀，类似比特币的地址生成格式
4. 已经在其他issue中描述
