### ISSUE TITLE
我发行的碳汇资产页面，显示信息错误

### ISSUE THREAD

**Issue by zhaohuijuan001** [ECO2Ledger/eco2-apps#24]
我发行的资产页面，列表显示信息错误：期望结果，请参考附件
1. 顶部发行商介绍文字，删除   -- 因为已经取消注册发行商环节，没有发行商信息
2. 资产列表中，没有碳汇项目，需要添加该项  -->列表中，应该包含我发行的：碳汇项目，碳汇资产，标准资产，并分别标示资产类型
3. 资产列表中，资产上限，可发行上限，可发行总量  -->修改为：资产上限，已发行总量 ，2项

**Comment by zhaohuijuan001** [comment]
![image](https://user-images.githubusercontent.com/61004114/96669399-bef65d80-138f-11eb-87d3-966abdc62951.png)
![image](https://user-images.githubusercontent.com/61004114/96669512-f6650a00-138f-11eb-9094-35780332846c.png)

**Comment by caosbad** [comment]
@zhaohuijuan001 已和青峰沟通过，不展示碳汇项目类型页面

**Comment by zhaohuijuan001** [comment]
问题1： 已修改
问题2： 同意沟通结果
问题3： 资产上限，可发行上限，可发行总量 -->修改为：资产上限，已发行总量 ，2项   --- 未实现

**Comment by zhaohuijuan001** [comment]
已修复，bug关闭
