### ISSUE TITLE
转账：资产名称不正确，只有年份

### ISSUE THREAD

**Issue by zhaohuijuan001** [ECO2Ledger/eco2-apps#31]
转账页面，下拉列表中，碳汇资产名称不正确，只有年份。  --》 应该显示全称：碳汇项目.年份， 类似MMNN.2020  
![image](https://user-images.githubusercontent.com/61004114/96841708-b29cfe00-147e-11eb-9558-e0fa00ab81a2.png)

**Comment by my9527** [comment]
需接口增加资产名称， 余额列表及资产详情(queryAsset) 都没有对应字段

**Comment by zhaohuijuan001** [comment]
10/26：bug 未修复，资产下拉列表，只显示年份

**Comment by zhaohuijuan001** [comment]
已修复，bug关闭
