### ISSUE TITLE
销毁碳汇资产页面，资产名称不正确，部分信息没有自动显示

### ISSUE THREAD

**Issue by zhaohuijuan001** [ECO2Ledger/eco2-apps#33]
销毁资产页面，有如下错误：
1. 碳汇资产名称不正确
2. 这些资产的信息，应该自动显示：资产年限，当前账户余额
3. 资产上限，改为“已发行总量”
4. 申请销毁数量，输入框预置文字为“请输入”
5. 下方勾选项：第2个，销毁资产会优先扣除...  --- 请删除这一行

![image](https://user-images.githubusercontent.com/61004114/96850266-32c86100-1489-11eb-8cfb-531164980609.png)

**Comment by caosbad** [comment]
@zhaohuijuan001 年限数据接口未提供，如果从其他的地方查询比较麻烦，建议后端补全，其余问题已解决

**Comment by zhaohuijuan001** [comment]
现在资产名称只显示年限，不是全称

**Comment by zhaohuijuan001** [comment]
青峰：请看一下 -- 年限数据接口未提供，如果从其他的地方查询比较麻烦，建议后端补全，其余问题已解决

**Comment by my9527** [comment]
done

**Comment by zhaohuijuan001** [comment]
bug已修复，关闭
