### ISSUE TITLE
碳汇资产详情页，显示信息错误

### ISSUE THREAD

**Issue by zhaohuijuan001** [ECO2Ledger/eco2-apps#34]
碳汇资产详情页，显示信息错误：
1. 资产名称不正确
2. 收款地址：应该显示收款地址，复制按钮，二维码标识
3. 最近交易列表，显示的内容应该按需求实现，请参考下方图片

![image](https://user-images.githubusercontent.com/61004114/96851418-943cff80-148a-11eb-810f-e941a2715956.png)

![image](https://user-images.githubusercontent.com/61004114/96850955-05c87e00-148a-11eb-94b5-5bdea932699a.png)

**Comment by zhaohuijuan001** [comment]
![image](https://user-images.githubusercontent.com/61004114/96851599-c64e6180-148a-11eb-937e-578ad45397dc.png)

**Comment by zhaohuijuan001** [comment]
![image](https://user-images.githubusercontent.com/61004114/96851737-ee3dc500-148a-11eb-8974-9d36bfe170e4.png)

**Comment by my9527** [comment]
done;
最近交易暂无接口，放置空列表

**Comment by zhaohuijuan001** [comment]
最近交易暂无接口，放置空列表  --- 另提新bug跟踪，这个bug关闭
