### ISSUE TITLE
转账碳汇资产时，总量会显示奇怪的十六进制数

### ISSUE THREAD

**Issue by zhaohuijuan001** [ECO2Ledger/eco2-apps#37]
转账碳汇资产时，总量会显示奇怪的十六进制数

步骤：
用户Bob，选择转账 “2020资产”，查看界面显示

![image](https://user-images.githubusercontent.com/61004114/96859562-3ad9ce00-1494-11eb-9017-ec236c8a4068.png)

**Comment by my9527** [comment]
done

**Comment by zhaohuijuan001** [comment]
bug已修复，关闭
