### ISSUE TITLE
转账碳汇资产时，总量数值不正确

### ISSUE THREAD

**Issue by zhaohuijuan001** [ECO2Ledger/eco2-apps#38]
转账碳汇资产时，总量的数量不正确

步骤：
Alice选择转账碳汇资产2020， 总量显示为2,300,000。
通过接口查询，该资产发行总量为2,300,000，Alice的账户余额为1,394,590。 传错了字段
issueId = '0x037d335e5085e089fc71faa3127ad93f2cf7cfc3afb56a5c027e9b300b254632'

**Comment by my9527** [comment]
done

**Comment by zhaohuijuan001** [comment]
bug已修复，关闭
