### ISSUE TITLE
碳汇资产详情页，账户的余额不正确

### ISSUE THREAD

**Issue by zhaohuijuan001** [ECO2Ledger/eco2-apps#46]
碳汇资产详情页，账户的余额不正确

用户Alice，余额显示： 1,200,000,496,777
通过接口查询，余额应该为：1,396,989
![image](https://user-images.githubusercontent.com/61004114/96964194-9eb7d180-153c-11eb-8902-4fd6f16dd163.png)

**Comment by cryptomancc** [comment]
命令行与前端查询数据不一致的情况，前端更新polkadot.js版本
