### ISSUE TITLE
用户挂卖单，发布后，锁定的金额与交易的总量不符

### ISSUE THREAD

**Issue by zhaohuijuan001** [ECO2Ledger/eco2-apps#47]
用户alice, 持有碳汇资产MMNN（2020） 共：1,199,999,990,000
发布卖单，交易总量为：90000， 发布后，alice 的账户余额为： 1,199,999,899,000
与发布订单之前相比，资产减少了91000. 

oderid: 0x84e23a8b03c5d8b4b9ba4b9595ad51e72af93fbe003b5c36c070370e307af243

**Comment by zhaohuijuan001** [comment]
![image](https://user-images.githubusercontent.com/61004114/96986170-df6f1500-1553-11eb-987b-b310b24d656b.png)

**Comment by cryptomancc** [comment]
无法重现。
挂单前，余额为，1,199,999,895,000，挂了一个90000的买单后，余额为1,199,999,805,000
