### ISSUE TITLE
买单成交后，双方账户的ECO2金额不正确，买方没有扣除ECO2, 卖方没有获得收益

### ISSUE THREAD

**Issue by zhaohuijuan001** [ECO2Ledger/eco2-apps#49]
用户bob 挂买单，参数如下： makeOrder(api, bob, assetId, moneyId, '20', '5000', 1, Date.now());

步骤：
1. 其他用户摘单前，查询双方账户余额
2. 用户alice 摘单，全部成交
3. 再次查询双方余额
余额变化情况如下：
Alice： 
ECO2     644921292482096731    -> 644921292357196584      差值：减少 124,900,147  （仅扣除手续费）
碳汇资产：   1,199,999,899,000   -> 1,199,999,894,000     差值： 减少 5000

Bob：
ECO2      1063921498856668687   ->   1063921498856668687     差值：  0
碳汇资产     10,000    ->   15,000      差值：多了5000

问题总结如下：
买方没有扣除ECO2, 卖方没有获得收益

**Comment by cryptomancc** [comment]
1. 如果用户挂买单，会锁定ECO2到一个暂存账户，所以成交后就不用再减少余额了，你应该算挂单前与成交后的差值
2.  124,900,147 包括手续费与成交的ECO2

**Comment by zhaohuijuan001** [comment]
10:26 测试结果：
BOB通过接口挂卖单，命令如下：价格 5000g/ECO2, 总量190000， 预计收益为：38ECO2.
makeOrder(api, bob, assetId, moneyId, '5000', '190000', 0, Date.now());
买卖成交后，买方Alice，账户余额：5,296,112,487 -> 5,296,112,477, 只减少了10ECO2. 
请调查原因

**Comment by zhaohuijuan001** [comment]
通过接口测试，买/卖交易，成交后，双方的金额变更都正确。 bug关闭
