### ISSUE TITLE
撤单后，历史挂单中，仍显示该订单，但是数量、价格、方向不能正常显示

### ISSUE THREAD

**Issue by zhaohuijuan001** [ECO2Ledger/eco2-apps#54]
前提：用户发布了一个买单

步骤：未交易的情况下，撤单
结果：历史挂单列表中，仍显示该订单，但是数量、价格、方向不能正常显示
期望结果：订单撤销后，应该在历史订单中显示，并且为“已撤销”的状态
![image](https://user-images.githubusercontent.com/61004114/97142442-97daca00-179b-11eb-929e-c54a8bf69713.png)

**Comment by zhaohuijuan001** [comment]
![image](https://user-images.githubusercontent.com/61004114/97142571-d1abd080-179b-11eb-9801-d6a7bad62663.png)

**Comment by my9527** [comment]
历史订单查询详情未返回 , 应该是接口问题

**Comment by zhaohuijuan001** [comment]
这个问题暂时pending, 待按照新的原型实现后，再看

**Comment by zhaohuijuan001** [comment]
根据新的原型，不再有历史挂单选项，因此该bug关闭
