### ISSUE TITLE
使用接口挂卖单，价格5000g/ECO2, 界面显示的价格为 0/g

### ISSUE THREAD

**Issue by zhaohuijuan001** [ECO2Ledger/eco2-apps#55]
BOB使用接口挂卖单，价格5000g/ECO2, 界面显示的价格为 0/g
问题如下：
1. 卖碳汇，价格的单位应该为 xxxg/ECO2, 而不是 0/g。
2. 价格的数量不正确，请改正
![image](https://user-images.githubusercontent.com/61004114/97153949-41c35200-17ae-11eb-81fd-028db3183f02.png)

**Comment by my9527** [comment]
done

**Comment by zhaohuijuan001** [comment]
bug关闭，价格显示相关的问题，用bug66跟踪
