### ISSUE TITLE
买得碳汇后，钱包页面中，碳汇资产显示为空

### ISSUE THREAD

**Issue by zhaohuijuan001** [ECO2Ledger/eco2-apps#57]
BOB买入碳汇5000000， 成交后，发现钱包页面，碳汇资产为空
但是，其他页面，如：碳汇资产详情页，可以正常显示

![image](https://user-images.githubusercontent.com/61004114/97160552-7ab3f480-17b7-11eb-84de-c9de1ad5a586.png)
![image](https://user-images.githubusercontent.com/61004114/97160667-a636df00-17b7-11eb-823e-175509e757e4.png)

**Comment by zhaohuijuan001** [comment]
此时，去碳汇转账，或者碳中和，都不能看到这个资产

**Comment by my9527** [comment]
接口未返回对应的碳汇资产

**Comment by zhaohuijuan001** [comment]
请青峰看一下，仍存在问题，11.3复测结果如下：
fredie 从alice处购买碳汇资产ICRT（2020）共1吨，从碳汇资产详情中可以看到该资产。
但是钱包页面，碳中和，碳汇转账等页面，无法看到该资产
![image](https://user-images.githubusercontent.com/61004114/97961091-976eae80-1ded-11eb-9859-e79a3ea73ddb.png)

**Comment by zhaohuijuan001** [comment]
bug仍复现，状态改为in progress

**Comment by zhaohuijuan001** [comment]
bug已修复，关闭
