### ISSUE TITLE
注册碳汇资产，资产名称应自动填写

### ISSUE THREAD

**Issue by zhaohuijuan001** [ECO2Ledger/eco2-apps#58]
注册碳汇资产，在选择碳汇项目后，资产名称应该自动填写，而非手动输入。
![image](https://user-images.githubusercontent.com/61004114/97284962-a0ef9800-187c-11eb-8e66-16b565727edc.png)

**Comment by my9527** [comment]
资产名称是用注册碳汇项目时候的那个？ 那自动填写后要不要允许手动改动

**Comment by zhaohuijuan001** [comment]
经确认，“资产名称”输入框删除，因为它跟“碳汇项目”是同一个

**Comment by my9527** [comment]
done

**Comment by zhaohuijuan001** [comment]
没有改呀，还在
![Uploading image.png…]()

**Comment by zhaohuijuan001** [comment]
bug已修复，关闭
