### ISSUE TITLE
从钱包>转账，无法取消，按钮不可点击

### ISSUE THREAD

**Issue by zhaohuijuan001** [ECO2Ledger/eco2-apps#60]
从钱包入口，选择某个碳汇资产，点击“转账”按钮。
点击“取消”，按钮不可点击，无法取消转账

![image](https://user-images.githubusercontent.com/61004114/97384513-c925d800-190a-11eb-8121-2e60c3f46aa7.png)

**Comment by my9527** [comment]
done

**Comment by zhaohuijuan001** [comment]
bug已修复，关闭
