### ISSUE TITLE
简化显示转账页面

### ISSUE THREAD

**Issue by zhaohuijuan001** [ECO2Ledger/eco2-apps#61]
简化显示转账页面，改动如下：
1. 总量：下拉列表可以选择单位  --》 取消下拉菜单，只支持ECO2 这一个单位
2. 我们是否需要支持“存在押金”这一项，必须账户余额高于某个值才存在？

![image](https://user-images.githubusercontent.com/61004114/97386389-aa294500-190e-11eb-8ca6-561bfdfde311.png)

**Comment by my9527** [comment]
done

**Comment by zhaohuijuan001** [comment]
bug关闭
