### ISSUE TITLE
钱包页面，资产列表排列不整齐

### ISSUE THREAD

**Issue by zhaohuijuan001** [ECO2Ledger/eco2-apps#73]
钱包页面，资产列表排列不整齐，请调整
![image](https://user-images.githubusercontent.com/61004114/97827803-4af97500-1d00-11eb-8496-7ecf94a741eb.png)

**Comment by my9527** [comment]
down

**Comment by zhaohuijuan001** [comment]
仍存在问题：没有水平对齐
其他用户，有多个碳汇资产时，中间有大片空白，请看图

![image](https://user-images.githubusercontent.com/61004114/97957845-f67cf500-1de6-11eb-85bb-62d89d3ecae6.png)

![image](https://user-images.githubusercontent.com/61004114/97957800-dea57100-1de6-11eb-9092-7c752e040df3.png)

**Comment by zhaohuijuan001** [comment]
11.4，新增问题：碳汇资产的排序也不正确 --> 应该是：根据碳汇资产的注册顺序排序
![image](https://user-images.githubusercontent.com/61004114/98065907-875bdb00-1e90-11eb-82e4-abc6423e0976.png)

**Comment by zhaohuijuan001** [comment]
bug已修复
