### ISSUE TITLE
注册碳汇项目，内容调整

### ISSUE THREAD

**Issue by zhaohuijuan001** [ECO2Ledger/eco2-apps#75]
注册碳汇项目页面，用户需要输入一系列信息，内容调整如下：
1. 注册碳汇项目，放在注册碳汇资产的左方。
2. 注册碳汇项目说明：按下方“ECO2 Ledger 中关于缺省⽂案的部分”中的文字显示
3. 完善信息部分，请按照图片标注的部分修改

碳汇项目说明：
在将碳汇资产上链⾄ECO2 Ledger前，请先完善预备上链的碳汇项⽬之基础信息。依照碳汇 项⽬之报告，如实完成下⽅信息填写，为提⾼碳汇项⽬的辨识度，请尽可能完成每个栏位的 信息填写，以便资产审查委员会审核。此申请⽆法撤回与修改，故请谨慎填写。⽬前ECO2 Ledger仅⽀持VCS (Verified Carbon Standard) 和GS (Gold Standard) 的碳标准申请上链，其他 碳标准之碳汇资产暂不⽀持。
![image](https://user-images.githubusercontent.com/61004114/97854199-19020600-1d34-11eb-87d2-9f069bf96cc6.png)

![image](https://user-images.githubusercontent.com/61004114/97854127-ff60be80-1d33-11eb-8009-4ea323588bf4.png)

**Comment by zhaohuijuan001** [comment]
项⽬类型 Project Type 总共有16种
1. 能源(可再⽣/不可再⽣) Energy (renewable/non-renewable) 
2. 能源分配 Energy distribution 
3. 能源需求 Energy demand 
4. 制造业 Manufacturing idustries 
5. 化学⼯业 Chemical industry 
6. 建筑业 Construction 
7. 交通 Transport 
8. 采矿业/矿业 Mining/Mineral production 
9. ⾦属制造 Metal production 
10. 燃料⻜逸性排放 Fugitive emissions from fuels 
11. ⼯业⽓体⻜逸性排放 Fugitive emissions from idustrial gases 
12. 溶剂使⽤ Solvents use 
13. 废弃物处⾥与填埋 Waste handling and disposal 
14. 农业，林业，⼟地利⽤ Agriculture, Forestry, Land Use 
15. 畜牧与肥料管理 Livestock and manure management 
16. Other 其他

**Comment by my9527** [comment]
done

**Comment by zhaohuijuan001** [comment]
注册碳汇项目，完善信息部分，已经按要求修改，bug关闭。
问题1,2 未修改，另提bug跟踪
