### ISSUE TITLE
注册碳汇资产页面，内容调整如下

### ISSUE THREAD

**Issue by zhaohuijuan001** [ECO2Ledger/eco2-apps#76]
注册碳汇资产页面，内容调整如下：
1. 注册碳汇资产说明，请按照“ECO2 Ledger 中关于缺省⽂案的部分”显示，文字见附件
2. 完善信息部分，请按照图片修改

![image](https://user-images.githubusercontent.com/61004114/97855154-531fd780-1d35-11eb-9600-818a2cf8abab.png)
[2_ECO2 Ledger 中关于缺省文案的部分（补充后）.pdf](https://github.com/ECO2Ledger/eco2-apps/files/5474108/2_ECO2.Ledger.pdf)

**Comment by my9527** [comment]
done

**Comment by zhaohuijuan001** [comment]
问题1，未修改，另提bug跟踪
问题2，已修复，bug关闭
