### ISSUE TITLE
碳中和页面，所在国家应该为国家列表

### ISSUE THREAD

**Issue by zhaohuijuan001** [ECO2Ledger/eco2-apps#77]
碳中和页面，内容调整如下：细节请看图片
1. 抵消人名称，调整为：抵消受益人名称
2. 所在国家，调整为：国家列表

![image](https://user-images.githubusercontent.com/61004114/97855815-4a7bd100-1d36-11eb-8c5c-be4cd8eb7fa2.png)

**Comment by zhaohuijuan001** [comment]
问题1，已修改
问题2：所在国家，调整为：国家列表 -- 未实现，需要修改

**Comment by my9527** [comment]
done

**Comment by zhaohuijuan001** [comment]
国家列表，需要更新一下，台湾显示为“中华民国（台湾）”，涉及敏感词条。
![image](https://user-images.githubusercontent.com/61004114/99354464-745df780-28e1-11eb-99ef-80bdbdfe28af.png)

**Comment by zhaohuijuan001** [comment]
香港-> 中国（香港），澳门-> 中国（澳门），请改一下这2项

**Comment by zhaohuijuan001** [comment]
bug已修复，关闭
