### ISSUE TITLE
碳汇资产详情页中，资产介绍不正确

### ISSUE THREAD

**Issue by zhaohuijuan001** [ECO2Ledger/eco2-apps#80]
碳汇资产详情页中，资产介绍当前显示：资产介绍说明。
期望结果：显示用户注册碳汇资产时，输入的“描述”部分。
比如ICRT（2012），注册时描述为“发行碳汇资产ICRT（2012）”
![image](https://user-images.githubusercontent.com/61004114/97956136-dcd9ae80-1de2-11eb-8b5a-69316921705d.png)
![image](https://user-images.githubusercontent.com/61004114/97956165-eebb5180-1de2-11eb-8481-f3c811599596.png)

**Comment by my9527** [comment]
done

**Comment by zhaohuijuan001** [comment]
bug已修复，关闭
