### ISSUE TITLE
注册/增发/销毁碳汇资产，均应为整数“吨”

### ISSUE THREAD

**Issue by zhaohuijuan001** [ECO2Ledger/eco2-apps#85]
真实世界的碳汇，划转操作等都是以吨为单位，所以链上也应该有此限制：
如果以克为单位，应该是1000000的整数倍；
如果以吨为单位，应该是整数。

1. 注册碳汇项目，编辑“项目碳汇总数”，和“预估年减排量”
2. 注册碳汇资产，编辑“项目发行数量”
3. 增发碳汇资产，编辑“申请增发数量”
4. 销毁碳汇资产，编辑“申请销毁数量”

**Comment by my9527** [comment]
done

**Comment by zhaohuijuan001** [comment]
bug已修复，关闭
