### ISSUE TITLE
注册碳汇项目，按钮的位置不正确，应该在左边

### ISSUE THREAD

**Issue by zhaohuijuan001** [ECO2Ledger/eco2-apps#89]
“注册碳汇项目” 按钮的位置，应该在“注册碳汇资产”的左方。先有项目，后有资产。包含以下错误页面：
1. 碳汇>碳汇资产页面
2. 碳汇>我发行的碳汇资产页面
3. 碳汇资产详情页

![image](https://user-images.githubusercontent.com/61004114/98508390-61707500-229a-11eb-8eae-cbfc03c50bb5.png)
![image](https://user-images.githubusercontent.com/61004114/98508642-cc21b080-229a-11eb-8101-64732e3334b3.png)
![image](https://user-images.githubusercontent.com/61004114/98508731-f70c0480-229a-11eb-9e7b-91b1193d01de.png)

**Comment by my9527** [comment]
done

**Comment by zhaohuijuan001** [comment]
bug已修复，关闭
