### ISSUE TITLE
销毁碳汇资产，“当前账户余额”应该以“吨”为单位

### ISSUE THREAD

**Issue by zhaohuijuan001** [ECO2Ledger/eco2-apps#91]
销毁碳汇资产页面，自动显示“当前账户余额”，应该以“吨”为单位。不足1吨的部分，显示为小数。
这样与其他数量，显示方式一致
![image](https://user-images.githubusercontent.com/61004114/98516450-799ac100-22a7-11eb-9051-4aee3f14c8be.png)

**Comment by my9527** [comment]
done

**Comment by zhaohuijuan001** [comment]
Bug未完全修复，当前账户余额：已经以“吨”为单位显示，但是没有显示“小数”部分
如alice ：
MW(2015) - 持有量： 108,499,999， 销毁碳汇时，当前账户余额： 108 ，应该显示为： 108.499999

**Comment by zhaohuijuan001** [comment]
bug已修复，关闭
